Copy Chef files around during Chef setup
Keep the ZTP post-install as ZTP specific as possible; have the chef-server
post-install do the copying of files.

diff --git a/pkgs/workbench/cldemo-wbench-chefserver/debian/DEBIAN/postinst b/pkgs/workbench/cldemo-wbench-chefserver/debian/DEBIAN/postinst
--- a/pkgs/workbench/cldemo-wbench-chefserver/debian/DEBIAN/postinst
+++ b/pkgs/workbench/cldemo-wbench-chefserver/debian/DEBIAN/postinst
@@ -1,6 +1,17 @@
 #!/usr/bin/env bash
 chef-server-ctl reconfigure
 
+if [[ -f /etc/chef-server/chef-validator.pem ]]; then
+  cp /etc/chef-server/chef-validator.pem /var/www/chef-validator.pem
+  chmod 644 /var/www/chef-validator.pem
+else
+  echo "Couldn't find /etc/chef/chef-validator.pem" >&2
+fi
+
+if [[ ! -f /etc/chef/validator.pem ]]; then
+  cp /etc/chef-server/chef-validator.pem /etc/chef/validation.pem
+fi
+
 # On the wbench, Apache listens on 80, switch Chef to a different port
 sed -i /var/opt/chef-server/nginx/etc/nginx.conf -e 's!listen 80!listen 8080!'
 sleep 5
